// cluster_message.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.0
// source: cluster_messages.proto

package cluster

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateActor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActorName         string `protobuf:"bytes,1,opt,name=actorName,proto3" json:"actorName,omitempty"`
	ConnectionAddress string `protobuf:"bytes,2,opt,name=connectionAddress,proto3" json:"connectionAddress,omitempty"`
	Forwarded         bool   `protobuf:"varint,3,opt,name=forwarded,proto3" json:"forwarded,omitempty"`
}

func (x *CreateActor) Reset() {
	*x = CreateActor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cluster_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateActor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateActor) ProtoMessage() {}

func (x *CreateActor) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateActor.ProtoReflect.Descriptor instead.
func (*CreateActor) Descriptor() ([]byte, []int) {
	return file_cluster_messages_proto_rawDescGZIP(), []int{0}
}

func (x *CreateActor) GetActorName() string {
	if x != nil {
		return x.ActorName
	}
	return ""
}

func (x *CreateActor) GetConnectionAddress() string {
	if x != nil {
		return x.ConnectionAddress
	}
	return ""
}

func (x *CreateActor) GetForwarded() bool {
	if x != nil {
		return x.Forwarded
	}
	return false
}

type DeleteActor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActorName string `protobuf:"bytes,1,opt,name=actorName,proto3" json:"actorName,omitempty"`
}

func (x *DeleteActor) Reset() {
	*x = DeleteActor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cluster_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteActor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteActor) ProtoMessage() {}

func (x *DeleteActor) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteActor.ProtoReflect.Descriptor instead.
func (*DeleteActor) Descriptor() ([]byte, []int) {
	return file_cluster_messages_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteActor) GetActorName() string {
	if x != nil {
		return x.ActorName
	}
	return ""
}

type MessageActor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActorName string     `protobuf:"bytes,1,opt,name=actorName,proto3" json:"actorName,omitempty"`
	Message   *anypb.Any `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *MessageActor) Reset() {
	*x = MessageActor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cluster_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageActor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageActor) ProtoMessage() {}

func (x *MessageActor) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageActor.ProtoReflect.Descriptor instead.
func (*MessageActor) Descriptor() ([]byte, []int) {
	return file_cluster_messages_proto_rawDescGZIP(), []int{2}
}

func (x *MessageActor) GetActorName() string {
	if x != nil {
		return x.ActorName
	}
	return ""
}

func (x *MessageActor) GetMessage() *anypb.Any {
	if x != nil {
		return x.Message
	}
	return nil
}

type ActorCreated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ActorCreated) Reset() {
	*x = ActorCreated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cluster_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActorCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorCreated) ProtoMessage() {}

func (x *ActorCreated) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorCreated.ProtoReflect.Descriptor instead.
func (*ActorCreated) Descriptor() ([]byte, []int) {
	return file_cluster_messages_proto_rawDescGZIP(), []int{3}
}

func (x *ActorCreated) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ActorCreated) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_cluster_messages_proto protoreflect.FileDescriptor

var file_cluster_messages_proto_rawDesc = []byte{
	0x0a, 0x16, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x77, 0x0a, 0x0b,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x61,
	0x63, 0x74, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x61, 0x63, 0x74, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x11, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x6f, 0x72, 0x77, 0x61,
	0x72, 0x64, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x66, 0x6f, 0x72, 0x77,
	0x61, 0x72, 0x64, 0x65, 0x64, 0x22, 0x2b, 0x0a, 0x0b, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41,
	0x63, 0x74, 0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0x5c, 0x0a, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x41, 0x63, 0x74,
	0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x2e, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x3c, 0x0a, 0x0c, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x0b,
	0x5a, 0x09, 0x2e, 0x3b, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_cluster_messages_proto_rawDescOnce sync.Once
	file_cluster_messages_proto_rawDescData = file_cluster_messages_proto_rawDesc
)

func file_cluster_messages_proto_rawDescGZIP() []byte {
	file_cluster_messages_proto_rawDescOnce.Do(func() {
		file_cluster_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_cluster_messages_proto_rawDescData)
	})
	return file_cluster_messages_proto_rawDescData
}

var file_cluster_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cluster_messages_proto_goTypes = []any{
	(*CreateActor)(nil),  // 0: cluster.createActor
	(*DeleteActor)(nil),  // 1: cluster.deleteActor
	(*MessageActor)(nil), // 2: cluster.messageActor
	(*ActorCreated)(nil), // 3: cluster.actorCreated
	(*anypb.Any)(nil),    // 4: google.protobuf.Any
}
var file_cluster_messages_proto_depIdxs = []int32{
	4, // 0: cluster.messageActor.message:type_name -> google.protobuf.Any
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cluster_messages_proto_init() }
func file_cluster_messages_proto_init() {
	if File_cluster_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cluster_messages_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CreateActor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cluster_messages_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteActor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cluster_messages_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*MessageActor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cluster_messages_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ActorCreated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cluster_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cluster_messages_proto_goTypes,
		DependencyIndexes: file_cluster_messages_proto_depIdxs,
		MessageInfos:      file_cluster_messages_proto_msgTypes,
	}.Build()
	File_cluster_messages_proto = out.File
	file_cluster_messages_proto_rawDesc = nil
	file_cluster_messages_proto_goTypes = nil
	file_cluster_messages_proto_depIdxs = nil
}
