// swim_message.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.0
// source: swim_messages.proto

package cluster

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SwimState int32

const (
	SwimState_Alive      SwimState = 0
	SwimState_Suspicious SwimState = 1
	SwimState_Dead       SwimState = 2
)

// Enum value maps for SwimState.
var (
	SwimState_name = map[int32]string{
		0: "Alive",
		1: "Suspicious",
		2: "Dead",
	}
	SwimState_value = map[string]int32{
		"Alive":      0,
		"Suspicious": 1,
		"Dead":       2,
	}
)

func (x SwimState) Enum() *SwimState {
	p := new(SwimState)
	*p = x
	return p
}

func (x SwimState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SwimState) Descriptor() protoreflect.EnumDescriptor {
	return file_swim_messages_proto_enumTypes[0].Descriptor()
}

func (SwimState) Type() protoreflect.EnumType {
	return &file_swim_messages_proto_enumTypes[0]
}

func (x SwimState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SwimState.Descriptor instead.
func (SwimState) EnumDescriptor() ([]byte, []int) {
	return file_swim_messages_proto_rawDescGZIP(), []int{0}
}

type SwimPing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender string         `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Extras *SwimExtraInfo `protobuf:"bytes,2,opt,name=extras,proto3" json:"extras,omitempty"`
}

func (x *SwimPing) Reset() {
	*x = SwimPing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swim_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SwimPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwimPing) ProtoMessage() {}

func (x *SwimPing) ProtoReflect() protoreflect.Message {
	mi := &file_swim_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwimPing.ProtoReflect.Descriptor instead.
func (*SwimPing) Descriptor() ([]byte, []int) {
	return file_swim_messages_proto_rawDescGZIP(), []int{0}
}

func (x *SwimPing) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *SwimPing) GetExtras() *SwimExtraInfo {
	if x != nil {
		return x.Extras
	}
	return nil
}

type SwimAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender  string         `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	State   SwimState      `protobuf:"varint,2,opt,name=state,proto3,enum=cluster.SwimState" json:"state,omitempty"`
	Version int32          `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Extras  *SwimExtraInfo `protobuf:"bytes,4,opt,name=extras,proto3" json:"extras,omitempty"`
}

func (x *SwimAck) Reset() {
	*x = SwimAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swim_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SwimAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwimAck) ProtoMessage() {}

func (x *SwimAck) ProtoReflect() protoreflect.Message {
	mi := &file_swim_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwimAck.ProtoReflect.Descriptor instead.
func (*SwimAck) Descriptor() ([]byte, []int) {
	return file_swim_messages_proto_rawDescGZIP(), []int{1}
}

func (x *SwimAck) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *SwimAck) GetState() SwimState {
	if x != nil {
		return x.State
	}
	return SwimState_Alive
}

func (x *SwimAck) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SwimAck) GetExtras() *SwimExtraInfo {
	if x != nil {
		return x.Extras
	}
	return nil
}

type SwimIndirectPing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Receiver     string `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Intermediate string `protobuf:"bytes,2,opt,name=intermediate,proto3" json:"intermediate,omitempty"`
	Sender       string `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
}

func (x *SwimIndirectPing) Reset() {
	*x = SwimIndirectPing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swim_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SwimIndirectPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwimIndirectPing) ProtoMessage() {}

func (x *SwimIndirectPing) ProtoReflect() protoreflect.Message {
	mi := &file_swim_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwimIndirectPing.ProtoReflect.Descriptor instead.
func (*SwimIndirectPing) Descriptor() ([]byte, []int) {
	return file_swim_messages_proto_rawDescGZIP(), []int{2}
}

func (x *SwimIndirectPing) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *SwimIndirectPing) GetIntermediate() string {
	if x != nil {
		return x.Intermediate
	}
	return ""
}

func (x *SwimIndirectPing) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

type SwimIndirectAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Receiver string    `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Sender   string    `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	State    SwimState `protobuf:"varint,3,opt,name=state,proto3,enum=cluster.SwimState" json:"state,omitempty"`
	Version  int32     `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *SwimIndirectAck) Reset() {
	*x = SwimIndirectAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swim_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SwimIndirectAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwimIndirectAck) ProtoMessage() {}

func (x *SwimIndirectAck) ProtoReflect() protoreflect.Message {
	mi := &file_swim_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwimIndirectAck.ProtoReflect.Descriptor instead.
func (*SwimIndirectAck) Descriptor() ([]byte, []int) {
	return file_swim_messages_proto_rawDescGZIP(), []int{3}
}

func (x *SwimIndirectAck) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *SwimIndirectAck) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *SwimIndirectAck) GetState() SwimState {
	if x != nil {
		return x.State
	}
	return SwimState_Alive
}

func (x *SwimIndirectAck) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type SwimExtraInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemberAddress string    `protobuf:"bytes,1,opt,name=member_address,json=memberAddress,proto3" json:"member_address,omitempty"`
	MemberState   SwimState `protobuf:"varint,2,opt,name=member_state,json=memberState,proto3,enum=cluster.SwimState" json:"member_state,omitempty"`
	Version       int32     `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Ttl           int32     `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
}

func (x *SwimExtraInfo) Reset() {
	*x = SwimExtraInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swim_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SwimExtraInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwimExtraInfo) ProtoMessage() {}

func (x *SwimExtraInfo) ProtoReflect() protoreflect.Message {
	mi := &file_swim_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwimExtraInfo.ProtoReflect.Descriptor instead.
func (*SwimExtraInfo) Descriptor() ([]byte, []int) {
	return file_swim_messages_proto_rawDescGZIP(), []int{4}
}

func (x *SwimExtraInfo) GetMemberAddress() string {
	if x != nil {
		return x.MemberAddress
	}
	return ""
}

func (x *SwimExtraInfo) GetMemberState() SwimState {
	if x != nil {
		return x.MemberState
	}
	return SwimState_Alive
}

func (x *SwimExtraInfo) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SwimExtraInfo) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

type SwimNewGossiper struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemberAddress string    `protobuf:"bytes,1,opt,name=member_address,json=memberAddress,proto3" json:"member_address,omitempty"`
	MemberState   SwimState `protobuf:"varint,2,opt,name=member_state,json=memberState,proto3,enum=cluster.SwimState" json:"member_state,omitempty"`
	Version       int32     `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *SwimNewGossiper) Reset() {
	*x = SwimNewGossiper{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swim_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SwimNewGossiper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwimNewGossiper) ProtoMessage() {}

func (x *SwimNewGossiper) ProtoReflect() protoreflect.Message {
	mi := &file_swim_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwimNewGossiper.ProtoReflect.Descriptor instead.
func (*SwimNewGossiper) Descriptor() ([]byte, []int) {
	return file_swim_messages_proto_rawDescGZIP(), []int{5}
}

func (x *SwimNewGossiper) GetMemberAddress() string {
	if x != nil {
		return x.MemberAddress
	}
	return ""
}

func (x *SwimNewGossiper) GetMemberState() SwimState {
	if x != nil {
		return x.MemberState
	}
	return SwimState_Alive
}

func (x *SwimNewGossiper) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type StringMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *StringMessage) Reset() {
	*x = StringMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swim_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringMessage) ProtoMessage() {}

func (x *StringMessage) ProtoReflect() protoreflect.Message {
	mi := &file_swim_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringMessage.ProtoReflect.Descriptor instead.
func (*StringMessage) Descriptor() ([]byte, []int) {
	return file_swim_messages_proto_rawDescGZIP(), []int{6}
}

func (x *StringMessage) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_swim_messages_proto protoreflect.FileDescriptor

var file_swim_messages_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x77, 0x69, 0x6d, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x22, 0x52,
	0x0a, 0x08, 0x53, 0x77, 0x69, 0x6d, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x12, 0x2e, 0x0a, 0x06, 0x65, 0x78, 0x74, 0x72, 0x61, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x77, 0x69,
	0x6d, 0x45, 0x78, 0x74, 0x72, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x65, 0x78, 0x74, 0x72,
	0x61, 0x73, 0x22, 0x95, 0x01, 0x0a, 0x07, 0x53, 0x77, 0x69, 0x6d, 0x41, 0x63, 0x6b, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e,
	0x53, 0x77, 0x69, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x06, 0x65, 0x78,
	0x74, 0x72, 0x61, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x77, 0x69, 0x6d, 0x45, 0x78, 0x74, 0x72, 0x61, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x06, 0x65, 0x78, 0x74, 0x72, 0x61, 0x73, 0x22, 0x6a, 0x0a, 0x10, 0x53, 0x77,
	0x69, 0x6d, 0x49, 0x6e, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x1a,
	0x0a, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x74, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x22, 0x89, 0x01, 0x0a, 0x0f, 0x53, 0x77, 0x69, 0x6d, 0x49,
	0x6e, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x41, 0x63, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x28,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e,
	0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x77, 0x69, 0x6d, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x22, 0x99, 0x01, 0x0a, 0x0d, 0x53, 0x77, 0x69, 0x6d, 0x45, 0x78, 0x74, 0x72, 0x61,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x25, 0x0a, 0x0e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x35, 0x0a, 0x0c, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x12, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x77, 0x69, 0x6d,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x0b, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03,
	0x74, 0x74, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x74, 0x74, 0x6c, 0x22, 0x89,
	0x01, 0x0a, 0x0f, 0x53, 0x77, 0x69, 0x6d, 0x4e, 0x65, 0x77, 0x47, 0x6f, 0x73, 0x73, 0x69, 0x70,
	0x65, 0x72, 0x12, 0x25, 0x0a, 0x0e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x35, 0x0a, 0x0c, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x12, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x77, 0x69, 0x6d, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x0b, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x25, 0x0a, 0x0d, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x2a, 0x30, 0x0a, 0x09, 0x53, 0x77, 0x69, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x09,
	0x0a, 0x05, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x75, 0x73,
	0x70, 0x69, 0x63, 0x69, 0x6f, 0x75, 0x73, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x65, 0x61,
	0x64, 0x10, 0x02, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x3b, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_swim_messages_proto_rawDescOnce sync.Once
	file_swim_messages_proto_rawDescData = file_swim_messages_proto_rawDesc
)

func file_swim_messages_proto_rawDescGZIP() []byte {
	file_swim_messages_proto_rawDescOnce.Do(func() {
		file_swim_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_swim_messages_proto_rawDescData)
	})
	return file_swim_messages_proto_rawDescData
}

var file_swim_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_swim_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_swim_messages_proto_goTypes = []any{
	(SwimState)(0),           // 0: cluster.SwimState
	(*SwimPing)(nil),         // 1: cluster.SwimPing
	(*SwimAck)(nil),          // 2: cluster.SwimAck
	(*SwimIndirectPing)(nil), // 3: cluster.SwimIndirectPing
	(*SwimIndirectAck)(nil),  // 4: cluster.SwimIndirectAck
	(*SwimExtraInfo)(nil),    // 5: cluster.SwimExtraInfo
	(*SwimNewGossiper)(nil),  // 6: cluster.SwimNewGossiper
	(*StringMessage)(nil),    // 7: cluster.StringMessage
}
var file_swim_messages_proto_depIdxs = []int32{
	5, // 0: cluster.SwimPing.extras:type_name -> cluster.SwimExtraInfo
	0, // 1: cluster.SwimAck.state:type_name -> cluster.SwimState
	5, // 2: cluster.SwimAck.extras:type_name -> cluster.SwimExtraInfo
	0, // 3: cluster.SwimIndirectAck.state:type_name -> cluster.SwimState
	0, // 4: cluster.SwimExtraInfo.member_state:type_name -> cluster.SwimState
	0, // 5: cluster.SwimNewGossiper.member_state:type_name -> cluster.SwimState
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_swim_messages_proto_init() }
func file_swim_messages_proto_init() {
	if File_swim_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_swim_messages_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SwimPing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swim_messages_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SwimAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swim_messages_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*SwimIndirectPing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swim_messages_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*SwimIndirectAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swim_messages_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*SwimExtraInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swim_messages_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*SwimNewGossiper); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swim_messages_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*StringMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_swim_messages_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_swim_messages_proto_goTypes,
		DependencyIndexes: file_swim_messages_proto_depIdxs,
		EnumInfos:         file_swim_messages_proto_enumTypes,
		MessageInfos:      file_swim_messages_proto_msgTypes,
	}.Build()
	File_swim_messages_proto = out.File
	file_swim_messages_proto_rawDesc = nil
	file_swim_messages_proto_goTypes = nil
	file_swim_messages_proto_depIdxs = nil
}
