// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.0
// source: receiver.proto

package remote

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	RemoteReceiver_ReceiveMessage_FullMethodName = "/remote.RemoteReceiver/ReceiveMessage"
)

// RemoteReceiverClient is the client API for RemoteReceiver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RemoteReceiverClient interface {
	ReceiveMessage(ctx context.Context, in *Envelope, opts ...grpc.CallOption) (*Empty, error)
}

type remoteReceiverClient struct {
	cc grpc.ClientConnInterface
}

func NewRemoteReceiverClient(cc grpc.ClientConnInterface) RemoteReceiverClient {
	return &remoteReceiverClient{cc}
}

func (c *remoteReceiverClient) ReceiveMessage(ctx context.Context, in *Envelope, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, RemoteReceiver_ReceiveMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemoteReceiverServer is the server API for RemoteReceiver service.
// All implementations must embed UnimplementedRemoteReceiverServer
// for forward compatibility
type RemoteReceiverServer interface {
	ReceiveMessage(context.Context, *Envelope) (*Empty, error)
	mustEmbedUnimplementedRemoteReceiverServer()
}

// UnimplementedRemoteReceiverServer must be embedded to have forward compatible implementations.
type UnimplementedRemoteReceiverServer struct {
}

func (UnimplementedRemoteReceiverServer) ReceiveMessage(context.Context, *Envelope) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveMessage not implemented")
}
func (UnimplementedRemoteReceiverServer) mustEmbedUnimplementedRemoteReceiverServer() {}

// UnsafeRemoteReceiverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RemoteReceiverServer will
// result in compilation errors.
type UnsafeRemoteReceiverServer interface {
	mustEmbedUnimplementedRemoteReceiverServer()
}

func RegisterRemoteReceiverServer(s grpc.ServiceRegistrar, srv RemoteReceiverServer) {
	s.RegisterService(&RemoteReceiver_ServiceDesc, srv)
}

func _RemoteReceiver_ReceiveMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Envelope)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteReceiverServer).ReceiveMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemoteReceiver_ReceiveMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteReceiverServer).ReceiveMessage(ctx, req.(*Envelope))
	}
	return interceptor(ctx, in, info, handler)
}

// RemoteReceiver_ServiceDesc is the grpc.ServiceDesc for RemoteReceiver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RemoteReceiver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "remote.RemoteReceiver",
	HandlerType: (*RemoteReceiverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceiveMessage",
			Handler:    _RemoteReceiver_ReceiveMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "receiver.proto",
}
